# Generated by Django 3.0.6 on 2022-07-05 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COSMIC_measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_granularity', models.IntegerField()),
                ('PATH_FILE_UR', models.CharField(max_length=400)),
                ('level_of_decomposition', models.IntegerField()),
                ('scope', models.TextField()),
                ('measurement_purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='data_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('attributes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='object_of_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='non_functional_requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=150)),
                ('cosmic_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSERTION.COSMIC_measurement')),
            ],
        ),
        migrations.CreateModel(
            name='functional_user_requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=150)),
                ('cosmic_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSERTION.COSMIC_measurement')),
            ],
        ),
        migrations.CreateModel(
            name='functional_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.TextField(blank=True, null=True)),
                ('cosmic_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSERTION.COSMIC_measurement')),
            ],
        ),
        migrations.CreateModel(
            name='functional_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggering_event', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('functional_user_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSERTION.functional_user_requirement')),
            ],
        ),
        migrations.CreateModel(
            name='data_movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('sub_process_description', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField()),
                ('data_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSERTION.data_group')),
                ('functional_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSERTION.functional_process')),
            ],
        ),
        migrations.AddField(
            model_name='data_group',
            name='object_of_interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSERTION.object_of_interest'),
        ),
        migrations.CreateModel(
            name='ambiguous_requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=150)),
                ('cosmic_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INSERTION.COSMIC_measurement')),
            ],
        ),
    ]
