# Generated by Django 3.0.6 on 2022-07-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSERTION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmic_measurement',
            name='measurement_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cosmic_measurement',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
