# Generated by Django 3.0.6 on 2022-07-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSERTION', '0002_auto_20220705_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmic_measurement',
            name='PATH_FILE_UR_IN_SERVER',
            field=models.FileField(default=None, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cosmic_measurement',
            name='level_of_decomposition',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='cosmic_measurement',
            name='level_of_granularity',
            field=models.IntegerField(default=3),
        ),
    ]
