# Generated by Django 3.0.6 on 2022-07-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSERTION', '0005_auto_20220727_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmic_measurement',
            name='PATH_FILE_UR_IN_SERVER',
            field=models.FileField(default=None, upload_to='media'),
            preserve_default=False,
        ),
    ]
