# Generated by Django 3.0.6 on 2022-07-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INSERTION', '0007_auto_20220727_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmic_measurement',
            name='PATH_FILE_UR_IN_SERVER',
        ),
    ]
